// mf-angular/src/app/app.component.ts
import { Component } from "@angular/core";
import { ChatComponent } from "./chat.component";
import { ColorSwitcherComponent } from "./color-switcher.component";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [ChatComponent, ColorSwitcherComponent],
  template: `
    <h2>Angular Micro Frontend</h2>
    <app-chat />
    <app-color-switcher />
  `,
})
export class AppComponent {}

// mf-react/src/App.tsx
import { useEffect, useState } from "react";
import { Chat } from "./Chat";
import { API_REGISTER } from "./core/api-register";

function App() {
  const [color, setColor] = useState("#fff");

  useEffect(() => {
    API_REGISTER.register("react-set-color", setColor);
  }, []);

  return (
    <>
      <h2>React Micro Frontend</h2>
      <Chat color={color} />
    </>
  );
}

export default App;
