// mf-react/src/Chat.tsx
import { useState, useEffect, FormEvent } from "react";
import { MessageQueueListener, MESSAGE_QUEUE } from "./core/message-queue";

export function Chat(props: { color: string }) {
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState<string[]>([]);

  useEffect(() => {
    const listener: MessageQueueListener = (key, data) => {
      if (key === "chat") {
        setMessages((messages) => [...messages, data as string]);
      }
    };

    MESSAGE_QUEUE.subscribe(listener, { replay: true });

    return () => MESSAGE_QUEUE.unsubscribe(listener);
  }, []);

  const handleSubmit = (event: FormEvent) => {
    event.preventDefault();
    if (message) {
      MESSAGE_QUEUE.send("chat", message);
      setMessage("");
    }
  };

  return (
    <>
      <div style={{ backgroundColor: props.color }}>
        {messages.map((message, i) => (
          <pre key={i}>{message}</pre>
        ))}
      </div>

      <form onSubmit={handleSubmit}>
        <input value={message} onChange={(e) => setMessage(e.target.value)} />
      </form>
    </>
  );
}

// mf-angular/src/app/chat.component.ts
import { Component, inject, signal } from "@angular/core";
import { FormGroup, FormControl, ReactiveFormsModule } from "@angular/forms";
import { MESSAGE_QUEUE } from "./core/message-queue";

@Component({
  selector: "app-chat",
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    @for (message of messages(); track $index) {
      <pre>{{ message }}</pre>
    }
    <form [formGroup]="form" (ngSubmit)="sendMessage()">
      <input formControlName="message" />
    </form>
  `,
})
export class ChatComponent {
  #mq = inject(MESSAGE_QUEUE);

  form = new FormGroup({ message: new FormControl("") });
  messages = signal<string[]>([]);

  ngOnInit() {
    this.#mq.subscribe(this.listener, { replay: true });
  }

  ngOnDestroy() {
    this.#mq.unsubscribe(this.listener);
  }

  listener = (key: string, data: unknown) => {
    if (key === "chat") {
      this.messages.update((messages) => {
        return [...messages, data as string];
      });
    }
  };

  sendMessage() {
    const message = this.form.value.message;
    if (!message) return;

    this.#mq.send("chat", message);
    this.form.controls.message.setValue("");
  }
}
